name: CristalynePlugin
version: '1.0.0'
main: org.crateplugin.cristalynePlugin.Main
api-version: '1.21'
authors: [ Cristalyne ]
description: my personal plugin
website: https://github.com/Cristalyne

commands:
  settings:
    description: définie certain parametre du plugin
    permission: OP
    permission-message: §8[§9My_ideas§8] §cVous n'avez pas les permission {PermissionNeeded.OP}
